name: terraform-fmt
description: Rewrite terraform files into canonical format
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:282ede87350cce4ac85bd8e402e56e825ee1ddb8b8574fea5b869c39f1a50730
  entrypoint: /entrypoints/fmt.sh

branding:
  icon: globe
  color: purple
