name: terraform-fmt
description: Rewrite Terraform files into canonical format
author: Daniel Flook

inputs:
  path:
    description: Path to the Terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the Terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:59c93d952e56ba7526e0b69aabbb6feebe77b0f86117f655bef886f331405e58
  entrypoint: /entrypoints/fmt.sh

branding:
  icon: globe
  color: purple
