name: terraform-fmt
description: Rewrite terraform files into canonical format
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:b59ad5deb4b545f552bdc6cfa558fe4655e9b75d501dde8cb5a3f93a438fd519
  entrypoint: /entrypoints/fmt.sh

branding:
  icon: globe
  color: purple
