name: terraform-fmt
description: Rewrite Terraform files into canonical format
author: Daniel Flook

inputs:
  path:
    description: Path to the Terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the Terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:c1d5822c9b542f4816a0623599ea250714ecfc8811d2f7f3fcfe88453a689a67
  entrypoint: /entrypoints/fmt.sh

branding:
  icon: globe
  color: purple
